apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    tier: frontend
spec:
  containers:
  - image: darsh1998/week6app:1.1.1
    name: nodewebapp
    ports:
    - containerPort: 3000
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  